### ISSUE TITLE
Task Markdown File

### ISSUE THREAD

**Issue by abruns123** [ubsuny/CP1-24-HW3#1]
I think the first thing we should do is set up a markdown file with all the classical electrodynamic functions we'll be implementing so that we can assign tasks from that.

**Comment by kylemasc917** [comment]
I agree I will make an issue that can just be a list of suggested functions to be compiled into this markdown.

**Comment by laserlab** [comment]
Anyone wants to convert the jupyter file to a markdown for convenience?

**Comment by laserlab** [comment]
@abruns123 @kylemasc917 In general it is always better to suggest a change or concept with an accompanying PR so it can be merged right away as I did it with @zbpetersbuf file.
