### ISSUE TITLE
Test Driven Development: Failures First

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW3#11]
Since we were talking about unit testing today, I thought I would bring up the topic of Test-Driven Development (TDD).

The basics of TDD are as follows:
-Write your unit test first
-Make sure that whatever it tests, fails (very important!)
-Write the minimal amount of code needed to make it pass
-Repeat

The general idea is that by writing your tests first (and making sure that they fail), you are giving yourself some guiderails when it comes to actually writing the code. You no long need to draft out the problem in your head, because you have a tangible goal-- making the unit test pass!

There is a ton of literature on the topic (especially if you are interested in web development) but for now I'll just link these:
-[Simple Intro to TDD](https://www.freecodecamp.org/news/learning-to-test-with-python-997ace2d8abe/)
-[TDD in Python: A Beginner's Guide](https://www.datacamp.com/tutorial/test-driven-development-in-python)

If there's questions regarding how/why it works, feel free to comment or reach out to me directly.

![goat](https://github.com/user-attachments/assets/fe25a5e2-70e9-4b3b-80da-485c2e2f7433)

> Obey the [Goat](https://www.obeythetestinggoat.com/)

**Comment by laserlab** [comment]
Do you want to convert this little write up into a markdown so we can push it into the repository?

**Comment by avgagliardo** [comment]
Sure thing, I'll take care of that tonight. I'll close this thread in a day or two, or whenever I push the markdown version.
