### ISSUE TITLE
Unit Tests and Module Organization

### ISSUE THREAD

**Issue by jkblc** [ubsuny/CP1-24-HW3#15]
How should our module be organized. Should we have a separate directory for each module with different files for the function and the unit tests? That is my understanding according to python best practices.

**Comment by avgagliardo** [comment]
For now, I have been developing my module in its own directory which contains the python file(s), documentation, and unit tests. 

If we want to consolidate things like the documentation later on, that should be easy to do too.

**Comment by laserlab** [comment]
separate folders are fine, but then we have to enforce it so we don’t mix

**Comment by jkblc** [comment]
Sounds good
