### ISSUE TITLE
Isn't merging supposed to be blocked?

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW3#18]
Isn't merging being blocked till a review takes place this time?

**Comment by avgagliardo** [comment]
PR's are supposed to be reviewed before a merge. Not sure what the current permissions for the repo are, but if you can merge I would wait until its properly reviewed otherwise someone might miss out on their PR review points.

**Comment by laserlab** [comment]
Since I’m the maintainer, it’s not that critical but I put back the same ruleset as in the last homework to have that nice red cannot be merged
