### ISSUE TITLE
Who will be the maintainer of the repository?

### ISSUE THREAD

**Issue by abruns123** [ubsuny/CP1-24-HW3#2]
We need a maintainer for the repository. Do we have any volunteers?

**Comment by kylemasc917** [comment]
This should be decided by tomorrow and no later than Wednesday.

**Comment by laserlab** [comment]
I put a class mention in here so everybody should see this issue: @ubsuny/cp1-24

**Comment by laserlab** [comment]
If nobody wants to be the maintainer for this homework till tomorrow’s class, I will be maintainer again.

**Comment by kylemasc917** [comment]
I also don't mind doing it again if no one will volunteer, but I was under the impression it was meant as a one-time position.

**Comment by laserlab** [comment]
@kylemasc917 I don’t mind you doing it again, but from a leaning outcome it would be probably good to take a break for this Homework
