### ISSUE TITLE
Implementation of functional programming functions question.

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW3#20]
Would it be preferable if we had two separate modules one for each functional programming function or use both of them in the same module?

**Comment by laserlab** [comment]
only use one module, but it can have many functions

**Comment by laserlab** [comment]
think of the module as the library for your electrodynamics problem.

you can and it is also preferable to have a second module for the unit tests

**Comment by kylemasc917** [comment]
I've submitted a pull request under the given assumption from what you've described:
File containing all modules
-algorithm module that solves the ED problem using functional programming
-unit test for the algorithm

Is there anything else I am missing?

**Comment by laserlab** [comment]
Just had a look at your PR. While somewhat complex this works as a function in a function.

**Comment by laserlab** [comment]
You can have a look at the linting output of the check inside the PR for some ideas what is missing

**Comment by kylemasc917** [comment]
I have edited both files to improve linting output especially adding more docstrings.
