### ISSUE TITLE
Module Milestone Reminder

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW3#22]
Looks like we only have about 6 module milestones, so if you know which function you are going to implement please add a milestone for it.

I'll leave this up until Monday as a reminder.

**Comment by ojha-aditya** [comment]
I have just now added the one on Poynting vector

**Comment by avgagliardo** [comment]
Looking good, but at least 5 more to go everyone!

**Comment by kylemasc917** [comment]
I've submitted mine @laserlab can we get an @ mention for the class group in this issue?

**Comment by laserlab** [comment]
> I've submitted mine @laserlab can we get an @ mention for the class group in this issue?

Sure, everyone should be able to do an @ubsuny/cp1-24 no?

**Comment by Cosmos491** [comment]
To make things clear, I just have to add a milestone for the function I am going to implement ?

**Comment by avgagliardo** [comment]
> To make things clear, I just have to add a milestone for the function I am going to implement ?

Yep, just make a milestone for your function and we will be one closer to the goal.

**Comment by kylemasc917** [comment]
> > I've submitted mine @laserlab can we get an @ mention for the class group in this issue?
> 
> Sure, everyone should be able to do an @ubsuny/cp1-24 no?

It appears I can. I didn't want to overstep. I will keep that noted for the future. Thank you.

**Comment by laserlab** [comment]
> > > I've submitted mine @laserlab can we get an @ mention for the class group in this issue?
> > 
> > 
> > Sure, everyone should be able to do an @ubsuny/cp1-24 no?
> 
> It appears I can. I didn't want to overstep. I will keep that noted for the future. Thank you.

No problem at all to mention all.

**Comment by laserlab** [comment]
Since there were only 11 submissions so far I will scale the required milestone accordingly for grading.

**Comment by laserlab** [comment]
See https://github.com/ubsuny/CP1-24-HW3/commit/3f759b5248b840394bc9c4da7d3b888af5ae939f

**Comment by avgagliardo** [comment]
Sounds great, I will close this issue then. Thanks!

**Comment by avgagliardo** [comment]
woops, didnt mean to reopen!
