### ISSUE TITLE
HW pre-existing function classification

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW3#24]
@laserlab The function which we need to use in defining the Electrodynamics function needs to be used only in the first function or in both the functions?

**Comment by laserlab** [comment]
You have to implement a classical electrodynamics function as a python function and use this function as an argument in another function

**Comment by ojha-aditya** [comment]
And both functions have to be a separate module of their own?

**Comment by ojha-aditya** [comment]
Do we have to break the Electrodynamic function in the two functions or use the other function in unit tests?

**Comment by laserlab** [comment]
All in one module. Just the unit test should be in a separate file

**Comment by kylemasc917** [comment]
From what I came to conclude you can us multiple of the various functions of functional programming to implement an algorithm to solve the ED function you chose. This should be done as one file with a separate file as a unit test.

**Comment by ojha-aditya** [comment]
I understand now, thank you for the clarification.

**Comment by ojha-aditya** [comment]
Closing this issue as it is near deadline now.
