### ISSUE TITLE
Formula writing

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW3#26]
Can anyone tell, which online platform they use to write mathematical formula that we can use directly in documentation?

**Comment by avgagliardo** [comment]
Github uses LaTeX to render math, which a lot of people do manually but there are also plenty of editors/composers out there like [Texmaker](https://www.xm1math.net/texmaker/) or [Overleaf](https://www.overleaf.com/). Your mileage may vary.

Also, AI can be a really huge help when it comes to formatting LaTeX or finding specific/obscure functionalities.

**Comment by Priyanka-43** [comment]
In this case also, I was doing the same mistake. i did not put .md, that's why LaTex was not working. But it's fixed now.

**Comment by avgagliardo** [comment]
Even better, good fix!

**Comment by Priyanka-43** [comment]
Yes, Thankyou.
