### ISSUE TITLE
Collection of HW tasks for Electrodynamic Functions

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW3#3]
This issue is a place for people to suggest and compile simple functions from Electrodynamics that can be used in this assignment.

**Comment by kylemasc917** [comment]
Resistance in a wire s the one example already given.

**Comment by avgagliardo** [comment]
I think I'll do capacitive reactance.

**Comment by Priyanka-43** [comment]
Magnetic field of long straight wire.

**Comment by iglesias-cardinale** [comment]
Unless somebody else really wants this one, I'd like to do the electric potential at any point in space given a certain charge distribution.

**Comment by dnxjay** [comment]
Capacitance of a Parallel Plate Capacitor

**Comment by Tolani4** [comment]
I plan on implementing electric potential due to a point charge

**Comment by laserlab** [comment]
Pinning this and keeping it open for reference

**Comment by jkblc** [comment]
I plan to do magnetic force on a moving charge (Lorentz Force)

**Comment by HeshamElsaman** [comment]
I'm willing to calculate the surface charge density of a conducting spherical shell of radius (R) and constant potential (V).

**Comment by Cosmos491** [comment]
Since it was made clear that my task is not in conflict with anyone, it will be to calculate the electric field due to a single charge, and a net electric field due to multiple charges using functional programming.

**Comment by kylemasc917** [comment]
I can do the example one provided of resistance in a wire.

**Comment by ojha-aditya** [comment]
I can do Poynting vector calculations.

**Comment by dhamalakamal** [comment]
I will be calculating total equivalent resistances of circuit where resistances are connected in parallel

**Comment by abruns123** [comment]
I can calculate the electric field of a sphere with constant charge density.

**Comment by kylemasc917** [comment]
Closing at end of assignment

**Comment by haiderabbas007** [comment]
I worked on EM waves in a conductor
