### ISSUE TITLE
What is linting?

### ISSUE THREAD

**Issue by p-pxmpo** [ubsuny/CP1-24-HW3#31]
Can someone explain what linting is? Im seeing seeing some of the pull requests saying an "all checks have failed" message by something called pylint.

**Comment by avgagliardo** [comment]
Linting is the process of making your code conform to the stylistic guidelines that help keep code easy to read, maintain, and extend.

If you are interested check out [PEP8](https://peps.python.org/pep-0008/) which outlines the the conventions for writing software with python. 

The linter is usually a process where an automated worker goes through your code to analyze how closely it conforms to these guidelines.

**Comment by laserlab** [comment]
> Can someone explain what linting is? Im seeing seeing some of the pull requests saying an "all checks have failed" message by something called pylint.

we also have covered that in class in slides (on discord) and in a hands on session (see: ubnsuny/CompPyhys/ReviewPython/linting)

**Comment by p-pxmpo** [comment]
thank you
