### ISSUE TITLE
Creating a GitHub folder

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW3#36]
How can we move files directly to a new folder from codespace instead of having to come out of it and doing it manually?

**Comment by laserlab** [comment]
no idea what you mean. You can put your modules in a separate directory and call it like your module. See eg PR #23

**Comment by ojha-aditya** [comment]
I did that, sorry the above seems unclear I realized. I thought we have to create two separate modules and call them from different directory but as you mentioned in #24 it can be in a single module and the unit test could be the second one

**Comment by ojha-aditya** [comment]
Closing the issue now that it is resolved.
