### ISSUE TITLE
Add Milestones for each HW task

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW3#4]
I believe we should start working in milestones. Most of them should be the functions that we choose for the assignment and some we can migrate from previous homework assignments.

**Comment by kylemasc917** [comment]
I have added a Homework due date and a Pull Request due date to the milestones as discussed in class on Monday 10/7/24 as well as in the task outline.

**Comment by avgagliardo** [comment]
I will start thinking of some as well. I'm still wondering if doing a milestone per module makes sense for this type of project. It seems like it would make it easier to organize issues, at least in terms of tasks-per-module.

**Comment by kylemasc917** [comment]
I agree. It would at least start to give a good outline.

**Comment by laserlab** [comment]
I’m pinning this issue for reference
