### ISSUE TITLE
About PEP8 and Linting

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW3#43]
I see a lot of questions regarding PEP8 guidelines and linting so I thought I'd post some resources.

-[PEP8 Style Guideline](https://peps.python.org/pep-0008/) for Python
-[Python Style Guide](https://google.github.io/styleguide/pyguide.html) from Google
-[How to Lint in Visual Studio Code](https://code.visualstudio.com/docs/python/linting)
-[What is Linting?](https://www.reddit.com/r/learnpython/comments/eupr0j/what_is_linting/) discussion from reddit

If there's any direct questions feel free to post them here as well.

**Comment by haiderabbas007** [comment]
My PR had 'Pylint: All jobs have failed'. It seems unclear where to take my code from here. In particular, my code and unit tests are working perfectly fine on jupyter.
