### ISSUE TITLE
What is a good pylint score?

### ISSUE THREAD

**Issue by abruns123** [ubsuny/CP1-24-HW3#58]
What standard should I be judging pylint scores by? Is it okay for them to be around 8.5? I want to know this for the purpose of making my code better and knowing how to apply pylint scores to reviewing other peoples' code.

**Comment by p-pxmpo** [comment]
I also have the same question

**Comment by ojha-aditya** [comment]
Yeah, asked this in #33 myself.

**Comment by dnxjay** [comment]
8-10 is generally the goal but i believe for this we're attempting to get as close as possible to 10
