### ISSUE TITLE
Pull Request format

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW3#6]
Do we want to create a basic framework for how each function submitted via a pull request should be formatted. i.e. folder structure, etc. ?

**Comment by laserlab** [comment]
Very good idea. Here are some guidelines from github: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by laserlab** [comment]
@kylemasc917  you want to look to start this? How about just the github suggestions:
 - [reference to a related issue] (https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#referencing-issues-and-pull-requests) in your repository.
- description of the changes proposed in the pull request.
[@mentions](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams) of the person or team responsible for reviewing proposed changes.
