### ISSUE TITLE
what im thinking ill do

### ISSUE THREAD

**Issue by zbpetersbuf** [ubsuny/CP1-24-HW3#7]
Im planning on creating a function where if you give it 2 of either voltage, current or resistance, it would then spit out the third, my plan is for it to have a text box pop up but Ill need to figure that part out

**Comment by laserlab** [comment]
Be aware though that you have to implement your algorithm as a module. But feel free to add the text box pop up in a separate module.

**Comment by laserlab** [comment]
add label and milestone

**Comment by laserlab** [comment]
yes please see #4

**Comment by dnxjay** [comment]
assuming this can be closed
